sudo: required

language: python

services: 
  - docker

notifications:
    email:
        on_success: never
        on_failure: always

addons:
    apt:
        packages:
            - curl
            - openssh-client

install:
    - docker build -t aiida-docker-base .
    - docker run -d aiida-docker-base

# I just run a command with verdi that returns a zero error code to see if
# verdi is installed properly
script:
    - sleep 30 # wait 30 seconds till the container is ready
    - "export DOCKERID=`docker ps -qf 'ancestor=aiida-docker-base'`"
    - "echo \"Docker ID: $DOCKERID\""
    - "docker exec --tty --user aiida \"$DOCKERID\" /bin/bash -l -c 'verdi'"
